---
title: "03_construct_figuretable"
author: "Suguru Otani"
date: "2024-01-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load {.tabset}

```{r, echo=FALSE,results = "asis"}
rm(list = ls())
library(magrittr)
library(ggplot2)
# set constant ----
list_num_time <-
  c(
    #10,
    #20,
    #30,
    #40,
    50#,
    #100,
    #200
  )
for(nn in 1:length(list_num_time)){
    temp_nn <-
      list_num_time[nn]
    filename <-
      paste(
        "num_time_",
        temp_nn,
        sep = ""
      )
    cat(filename,"\n")
    temp_data <-
      readRDS(
        file =
          here::here(
            paste(
              "output/",
              "implied_efficiency_",
              filename,
              ".rds",
              sep = ""
            )
            )
        )
    assign(
      filename,
      temp_data)
}

options(modelsummary_format_numeric_latex = "plain") # for modelsummary output
```



## Stationary {.tabset}

the match elasticity with respect to unemployment is in the range 0.5–0.7.

### Bias and RMSE

```{r,echo=FALSE,results = "asis"}
temp <-
  num_time_50 %>% 
  dplyr::mutate(
    bias = normalized_efficiency*100 - efficiency_implied*100
    ) %>% 
  dplyr::group_by(
    simulation_id
  ) %>% 
  dplyr::summarise(
    mean_bias =
      mean(bias)
  ) %>% 
  dplyr::ungroup()
modelsummary::datasummary_skim(
  fmt = 3,
  temp)

```

### Elasticity dlogM/dlogU,dlogM/dlogV

```{r,echo=FALSE,results = "asis"}


```
